name: Compilar ESP-IDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Compilar con ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32c3
          path: 'firmware'
          command: |
            idf.py set-target esp32c3
            idf.py build

      - name: Subir binarios como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32c3
          path: |
            firmware/build/*.bin
            firmware/build/bootloader/*.bin
            firmware/build/partition_table/*.bin
