name: Compilar ESP-IDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Importante si tu proyecto usa submódulos

      - name: Compilar con ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3 # Aquí puedes especificar la versión exacta
          target: esp32c3 # Cambia el target según tu placa (esp32, esp32s3, esp32c3, etc.)
